apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: qeep8t62j-go-gitops
  description: This is GitOps manifest for qeep8t62j-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: qeep8t62j-go
    janus-idp.io/tekton: qeep8t62j-go
    backstage.io/kubernetes-id: qeep8t62j-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:qeep8t62j-go
