apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: qeep8t62j-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:cb2a9cad1fdd049024d7535def2994c5cedff0a2@sha256:60b0b8abdc9731bb98483eaaaf0997ceafd1e82cc115e6da2869ea458b8bb122
          name: container-image
